// <auto-generated />
namespace AspNetIdentitySample.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CountryColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CountryColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "202210250156013_CountryColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
